###
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/$metadata
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
###
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/
  ?$format=json
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
###
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/CountryVHSet
  ?$format=json
  &$top=10
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
###
# @name readBP
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/BPAddressSet
  ?$format=json
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
###
@bpID={{readBP.response.body.$.d.results[0].Partner}}
###
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/BPAddressSet('{{bpID}}')
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
Accept: application/json
###
# @name readBPAttachments
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/BPAddressSet('{{bpID}}')/to_Attachments
  ?$format=json
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
###
@mediaSrc={{readBPAttachments.response.body.d.results[0].__metadata.media_src}}
###
GET {{mediaSrc}}
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
