###
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/$metadata
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
###
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/
  ?$format=json
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
###
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/CountryVHSet
  ?$format=json
  &$top=10
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
###
# @name readBP
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/BPAddressSet
  ?$format=json
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
###
@bpID={{readBP.response.body.$.d.results[0].Partner}}
###
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/BPAddressSet('{{bpID}}')
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
Accept: application/json
###
# @name readBPAttachments
GET {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/BPAddressSet('{{bpID}}')/to_Attachments
  ?$format=json
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
###
@mediaSrc={{readBPAttachments.response.body.d.results[0].__metadata.media_src}}
@uri={{readBPAttachments.response.body.d.results[0].__metadata.uri}}
###
GET {{mediaSrc}}
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}

### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
X-CSRF-Token: Fetch
### Read Token to Variable
@csrf={{getCSRF.response.headers.x-csrf-token}}

### Upload File
# @name createAttachment
POST {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/BPAddressSet('{{bpID}}')/to_Attachments
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
X-CSRF-Token: {{csrf}}
Accept-Language: en
Accept: application/json
Content-Type: image/jpeg
Slug: Test.jpg

< ./Test.jpg
### Upload EICAR Test File
POST {{$dotenv backend_url}}/sap/opu/odata/sap/ZBP_SRV/BPAddressSet('{{bpID}}')/to_Attachments
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
X-CSRF-Token: {{csrf}}
Accept-Language: en
Accept: application/json
Content-Type: text/plain
Slug: Test.txt

X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
###
DELETE  {{uri}}
X-CSRF-Token: {{csrf}}
Accept: application/json
Authorization: Basic {{$dotenv backend_username}}:{{$dotenv backend_password}}
